version: "3"
services:
  apache:
    build:
      context: "."
      dockerfile: "Dockerfile-${PHP_VERSION}"
      args:
        - "SERVER_ROOT=${SERVER_ROOT}"
        - "PHP_VERSION=${PHP_VERSION}"
        - "DISPLAY_PHPERROR=${DISPLAY_PHPERROR}"
        - "MONGODB_VERSION=${MONGODB_VERSION}"
    volumes:
      - "${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX}${APP_CODE_CONTAINER_FLAG}"
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    volumes:
      - "${DATA_PATH_HOST}/mysql:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:3306"
  nodejs:
    build:
      context: ./nodejs
      target: sylius_nodejs
      # cache_from:
      #   - quay.io/sylius/nodejs:latest
      #   - quay.io/sylius/php:latest
    image: quay.io/sylius/nodejs:latest
    environment:
      - GULP_ENV=dev
      - APACHE_HOST_HTTP_PORT=80
      - PHP_HOST=apache
    volumes:
      - ${APP_CODE_PATH_HOST}:/srv/sylius:rw,cached
      - ${APP_CODE_PATH_HOST}/public:/srv/sylius/public:rw,delegated
    ports:
      - "35729:35729"
  mailhog:
    # do not use in production!
    image: mailhog/mailhog:latest
    environment:
      - MH_STORAGE=maildir
    # volumes:
    #   - ./docker/mailhog/maildir:/maildir:rw,delegated
    ports:
      - "8025:8025"
volumes: {}